# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: horchata_dev
  username: neilsethi
  password:
  host: localhost
 
test: &test
  adapter: postgresql
  database: horchata_dev_test
  username: neilsethi
  password:
  host: localhost
